
try {
    console.log('1');
    let a = b
    console.log('2');
} catch (error) {
    console.log(error);


}

